# Generated by Django 3.2.3 on 2021-05-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('movies', '0001_initial'),
        ('reviews', '0001_initial'),
        ('communities', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like_post',
            field=models.ManyToManyField(related_name='post_liked_user', to='communities.Post'),
        ),
        migrations.AddField(
            model_name='user',
            name='like_review',
            field=models.ManyToManyField(related_name='review_liked_user', to='reviews.Review'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='user',
            name='watch_movie',
            field=models.ManyToManyField(related_name='movie_watched_user', to='movies.Movie'),
        ),
    ]
